doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: UTF8
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            finance_portfolio:
                mapping: true
                type: xml
                dir: "%kernel.project_dir%/src/Finance/Portfolio/Infrastructure/Persistence/Doctrine"
                prefix: 'Finizens\Finance\Portfolio\Domain'
                is_bundle: false

when@test:
        # namespace is arbitrary but should be different from App\Migrations
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'
        orm:
            mappings:
                doctrine_repository_test_aggregate_root:
                    mapping: true
                    type: xml
                    dir: "%kernel.project_dir%/tests/Shared/Integration/Persistence/Doctrine/"
                    prefix: 'Tests\Shared\Integration\Persistence\Doctrine'
                    is_bundle: false
when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
