version: "3.8"

services:
    php:
        container_name: php
        build: ./docker/php
        volumes:
            - ./:/var/www/symfony
            - /var/www/symfony/front
        networks:
            - symfony

    nginx:
        container_name: nginx
        build: ./docker/nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

    db:
        container_name: db
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: finizens
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports: 
            - 3306:3306
        networks:
            - symfony

    front:
        container_name: front
        build:
            context: ./front
            dockerfile: Dockerfile
        volumes:
            - ./front:/app
            - /app/node_modules
        ports: 
            - 5173:5173
        networks:
            - symfony

networks:
    symfony:
